language: node_js
node_js:
  - "0.10"
after_success:
- ./node_modules/.bin/jscoverage lib lib-cov
- JS_COV=1 ./node_modules/.bin/mocha test/**.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js